// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Address: typeof import('./components/System/Address.vue')['default']
    AddressInput: typeof import('./components/Forms/AddressInput.vue')['default']
    AddressWithBlocky: typeof import('./components/System/AddressWithBlocky.vue')['default']
    Blockie: typeof import('./components/System/Blockie.vue')['default']
    Button: typeof import('./components/Forms/Button.vue')['default']
    Card: typeof import('./components/System/Card.vue')['default']
    CheckBoxInput: typeof import('./components/Forms/CheckBoxInput.vue')['default']
    Feedback: typeof import('./components/System/Feedback.vue')['default']
    Footer: typeof import('./components/App/Footer/Footer.vue')['default']
    FormInput: typeof import('./components/Forms/FormInput.vue')['default']
    Header: typeof import('./components/App/Header/Header.vue')['default']
    Menu: typeof import('./components/App/Header/Menu.vue')['default']
    Modal: typeof import('./components/App/Layout/modals/Modal.vue')['default']
    MoreDropdown: typeof import('./components/App/Header/MoreDropdown.vue')['default']
    NumberInput: typeof import('./components/Forms/NumberInput.vue')['default']
    Page: typeof import('./components/App/Layout/Page.vue')['default']
    PageContent: typeof import('./components/App/Layout/PageContent.vue')['default']
    PagePath: typeof import('./components/App/Layout/PagePath.vue')['default']
    README: typeof import('./components/README.md')['default']
    Spinner: typeof import('./components/System/Spinner.vue')['default']
    TextInput: typeof import('./components/Forms/TextInput.vue')['default']
    ToastList: typeof import('./components/System/ToastList.vue')['default']
    'Uil:twitter': typeof import('~icons/uil/twitter')['default']
  }
}

export { }
